# Welcome to the example configuration file! –í —ç—Ç–æ—Ç –ø–∏—à–µ–º
# Remember that if this is in bin/Content.Server or such, it may be overwritten on build.
# Consider copying it and using the --config-file and --data-dir options.

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = true

[net]
tickrate = 60
port = 1212
bindto = "::,0.0.0.0"
# Automatic port forwarding!
# Disabled by default because you may not want to do this.
# upnp = true

[status]
# The status server is the TCP side, used by the launcher to determine engine version, etc.
# To be clear: Disabling it makes the launcher unable to connect!
enabled = true
# This is the address and port the status server binds to.
# The port is by default set based on net.port so it will follow what you set there.
# # bind = "*:1212"
# This is the address of the SS14 server as the launcher uses it.
# This is only needed if you're proxying the status HTTP server -
#  by default the launcher will assume the address and port match that of the status server.
# connectaddress = "udp://localhost:1212"

[game]
hostname = "[RU][18+][FurryRp] - üêæMeowStationüêæ "
desc = "–§—É—Ä—Ä–∏ —Ä–ø —Å–µ—Ä–≤–µ—Ä —Å –ø–æ–Ω–∏–∂–µ–Ω–Ω—ã–º —É—Ä–æ–≤–Ω–µ–º —Ä–æ–ª–µ–≤–æ–≥–æ –æ—Ç—ã–≥—Ä—ã—â–∞ –∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å—é –ï–†–ü. \n –°–∫–æ—Ä–æ –æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ."
maxplayers = 100
lobbyenabled = true
soft_max_players = 100
lobbyduration = 180
maxcharacterslots = 5
cryo_sleep_rejoining = true
station_offset = false
station_rotation = false
round_restart_time = 180

[console]
# If this is true, people connecting from this machine (loopback)
# will automatically be elevated to full admin privileges.
# This literally works by checking if address == 127.0.0.1 || address == ::1
loginlocal = true

[hub]
# Set to true to show this server on the public server list
# Before enabling this, read: https://docs.spacestation14.io/hosts/hub-rules
advertise = true
# Comma-separated list of tags, useful for categorizing your server.
# See https://docs.spacestation14.io/hosts/hub-rules for more details on this when it becomes relevant.
tags = "rp:low, lang:ru, region:eu_e"
# URL of your server. Fill this in if you have a domain name,
# want to use HTTPS (with a reverse proxy), or other advanced scenarios.
# Must be in the form of an ss14:// or ss14s:// URI pointing to the status API.
server_url = ""

[build]
# *Absolutely all of these can be supplied using a "build.json" file*
# For further information, see https://github.com/space-wizards/space-station-14/blob/master/Tools/gen_build_info.py
# The main reason you'd want to supply any of these manually is for a custom fork and if you have no tools.
# Useful to override if the existing version is bad.
# See https://github.com/space-wizards/RobustToolbox/tags for version values, remove the 'v'.
# The value listed here is almost certainly wrong - it is ONLY a demonstration of format.
# engine_version = "0.7.6"
# This one is optional, the launcher will delete other ZIPs of the same fork to save space.
# fork_id = "abacusstation"
# Automatically set if self-hosting client zip, but otherwise use this when updating client build.
# There is no required format, any change counts as a new version.
# version = "Example1"
# This is where the launcher will download the client ZIP from.
# If this isn't supplied, the server will check for a file called "Content.Client.zip",
#  and will host it on the status server.
# If that isn't available, the server will attempt to find and use "../../Resources" and
#  "../../bin/Content.Client" to automatically construct a client zip.
# It will then host this on the status server.
# Note that these paths do not work on "FULL_RELEASE" servers.
# FULL_RELEASE servers expect to be used with a specific "packaged" layout.
# As such, whatever script you're using to package them is expected to create the ZIP.
# download_url = "http://example.com/compass.zip"
# Build hash - this is a *capitalized* SHA256 hash of the client ZIP.
# Optional in any case and automatically set if hosting a client ZIP.
# This hash is an example only.
# build = "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855"

[auth]
# Authentication (accounts):
# 0 = Optional, 1 = Required, 2 = Disabled
# Presumably do require authentication on any public server.
mode = 0
# If true, even if authentication is required, localhost is still allowed to login directly regardless.
# allowlocal = true
# You should probably never EVER need to touch this, but if you need a custom auth server,
# (the auth server being the one which manages Space Station 14 accounts), you change it here.
# server = https://central.spacestation14.io/auth/

[server]
rules_file = "RulesMeow"
[discord]
ahelp_webhook = "https://discord.com/api/webhooks/1091943500666380418/Jml3b-n2-MPcG0CKSronJ8d6sFTbfAXAS-a4j8zM35qQvH3RE3xkuv7k7TNItRyvQtxh"

[infolinks]
discord = "https://discord.gg/KTwBhQxYuF"
website = "https://goo.su/6iy4hC"
appeal = "https://discord.gg/KTwBhQxYuF"

[admin]
role_ban_default_severity = "high"
department_ban_default_severity = "high"
server_ban_default_severity = "high"
new_player_threshold = 60

[atmos]
space_wind = true
space_wind_max_velocity = 60
space_wind_max_push_force = 40
monstermos_rip_tiles = true
grid_impulse = true
mmos_spacing_speed = 0.1

[ooc]
enable_during_round = true

[vote]
restart_required_ratio = 0.51
timermap = 60

[procgen]
preload = false

[shuttle]
arrivals = false
emergency_early_launch_allowed = true
emergency_authorize_time = 15
emergency_transit_time_max = 90
recall_turning_point = 0.9
auto_call_time = 120
auto_call_extension_time = 30

[chat]
max_message_length = 2000
max_announcement_length = 512

[rules]
time = 30

[netres]
store_deletion_days = 15

[ic]
flavor_text = true

[salvage]
expedition_duration = 660
expedition_cooldown = 600

[worldgen]
enabled = true